export const NAV_LINKS = [
  { id: "home", label: "Home", type: "scroll", rotation: 8,
    hoverStyles: { bgColor: "#005F73", textColor: "#ffffff" }, },
  { id: "about", label: "About", type: "scroll", rotation: -8,
    hoverStyles: { bgColor: "#9B2226", textColor: "#ffffff" } },
  { id: "timeline", label: "Timeline", type: "scroll", rotation: 8,
    hoverStyles: { bgColor: "#EE9B00", textColor: "#ffffff" } },
  { id: "roles", label: "Roles", type: "scroll", rotation: -8,
    hoverStyles: { bgColor: "#CE2012", textColor: "#ffffff" } },
  { id: "prizes", label: "Prizes", type: "scroll", rotation: 8,
    hoverStyles: { bgColor: "#94D2BD", textColor: "#ffffff" }, },
  { id: "general-guidelines", label: "Guidelines", type: "scroll", rotation: -8,
    hoverStyles: { bgColor: "#0A9396", textColor: "#ffffff" }, },
  { id: "faqs", label: "FAQs", type: "scroll", rotation: 8,
    hoverStyles: { bgColor: "#C49F31", textColor: "#ffffff" }, },
  { id: "contact", label: "Contact", type: "scroll", rotation: 8,
    hoverStyles: { bgColor: "#E30B5C", textColor: "#ffffff" }, },
  // { id: "/shortlisted-teams", label: "Shortlisted Teams", type: "link", rotation: -8,
  //   hoverStyles: { bgColor: "#CA6702", textColor: "#ffffff" }, },
];